name: Lint Markdown

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
          fix: true

      - name: Commit and push fixes
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix markdown linting issues"
          commit_user_name: markdownlint-cli2-action
          commit_user_email: markdownlint-cli2-action@users.noreply.github.com
